flowchart LR
    A[Real World<br/> people, products]
    B[Application Model<br/> objects, APIs]
    C[Logical Data Model<br/> JSON, Tables]
    D[Physical Data Representation<br/> bytes in memory, disk, network]
    E[Hardware Level<br/> electrical signals, light, magnetism]

    A --> B
    B --> C
    C --> D
    D --> E